DROP TABLE blog_posts CASCADE;
DROP TABLE users CASCADE;

CREATE TABLE users (
    id serial PRIMARY KEY,
    user_name text NOT NULL,
    blog_name text NOT NULL,
    password text
);

CREATE TABLE blog_posts (
    id serial PRIMARY KEY,
    post_title text,
    blog_body text,
    post_date date NOT NULL,
    image_src text,
    blogger_id integer NOT NULL REFERENCES users(id)
);

INSERT INTO users (user_name, blog_name, password) VALUES ('Juan', 'Juan Travels', 'travel');
INSERT INTO users (user_name, blog_name, password) VALUES ('MengMeng', 'Meng Meng Cuisine', 'eatwithstyle23');
INSERT INTO users (user_name, blog_name, password) VALUES ('Tshepiso', 'Fashion Your Way', 'DressToImpress123');


INSERT INTO blog_posts (blogger_id, post_date, post_title, blog_body, image_src) 
VALUES ('1', '05/02/2021', 'My trip to Suriname', 'This was an amazing trip! One country barely anyone seems to know... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi gravida, massa at varius laoreet, ligula tellus convallis mauris, in dapibus ligula sem in odio. Mauris nisi elit, hendrerit vel diam in, congue molestie nibh. Praesent aliquet metus libero, eget scelerisque nisl ullamcorper ac. Nam eu nunc ex. Fusce ut dignissim felis. Mauris laoreet ante leo, vel aliquam est congue sed. Cras congue lectus vitae justo luctus efficitur. Nunc suscipit diam a felis dapibus gravida. Ut lobortis ultrices venenatis. Nunc aliquam luctus turpis faucibus consectetur. Praesent vitae maximus risus, vitae euismod nisl. In sagittis augue turpis, at cursus tellus condimentum in. Morbi vestibulum ultricies enim mattis ultrices. Etiam lobortis interdum ante vitae imperdiet. Phasellus dictum nisl massa, a rutrum quam hendrerit vel.', 'Suriname.jpg');
INSERT INTO blog_posts (blogger_id, post_date, post_title, blog_body, image_src) 
VALUES ('1', '03/25/2021', 'My trip to Seychelles', 'White sands, warm weather and kind people... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi gravida, massa at varius laoreet, ligula tellus convallis mauris, in dapibus ligula sem in odio. Mauris nisi elit, hendrerit vel diam in, congue molestie nibh. Praesent aliquet metus libero, eget scelerisque nisl ullamcorper ac. Nam eu nunc ex. Fusce ut dignissim felis. Mauris laoreet ante leo, vel aliquam est congue sed. Cras congue lectus vitae justo luctus efficitur. Nunc suscipit diam a felis dapibus gravida. Ut lobortis ultrices venenatis. Nunc aliquam luctus turpis faucibus consectetur. Praesent vitae maximus risus, vitae euismod nisl. In sagittis augue turpis, at cursus tellus condimentum in. Morbi vestibulum ultricies enim mattis ultrices. Etiam lobortis interdum ante vitae imperdiet. Phasellus dictum nisl massa, a rutrum quam hendrerit vel.', 'Seychelles.jpg');
INSERT INTO blog_posts (blogger_id, post_date, post_title, blog_body, image_src) 
VALUES ('1', '05/28/2021', 'My trip to South Africa', 'Being from the Southern Hemisphere originally I had always wanted to visit the Southern African region!... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi gravida, massa at varius laoreet, ligula tellus convallis mauris, in dapibus ligula sem in odio. Mauris nisi elit, hendrerit vel diam in, congue molestie nibh. Praesent aliquet metus libero, eget scelerisque nisl ullamcorper ac. Nam eu nunc ex. Fusce ut dignissim felis. Mauris laoreet ante leo, vel aliquam est congue sed. Cras congue lectus vitae justo luctus efficitur. Nunc suscipit diam a felis dapibus gravida. Ut lobortis ultrices venenatis. Nunc aliquam luctus turpis faucibus consectetur. Praesent vitae maximus risus, vitae euismod nisl. In sagittis augue turpis, at cursus tellus condimentum in. Morbi vestibulum ultricies enim mattis ultrices. Etiam lobortis interdum ante vitae imperdiet. Phasellus dictum nisl massa, a rutrum quam hendrerit vel.', 'CapeTown.jpg');
INSERT INTO blog_posts (blogger_id, post_date, post_title, blog_body, image_src) 
VALUES ('1', '12/11/2021', 'My trip to Kenya', 'Jambo from Nairobi! What a beautiful city with people who will go out of their way to greet you... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi gravida, massa at varius laoreet, ligula tellus convallis mauris, in dapibus ligula sem in odio. Mauris nisi elit, hendrerit vel diam in, congue molestie nibh. Praesent aliquet metus libero, eget scelerisque nisl ullamcorper ac. Nam eu nunc ex. Fusce ut dignissim felis. Mauris laoreet ante leo, vel aliquam est congue sed. Cras congue lectus vitae justo luctus efficitur. Nunc suscipit diam a felis dapibus gravida. Ut lobortis ultrices venenatis. Nunc aliquam luctus turpis faucibus consectetur. Praesent vitae maximus risus, vitae euismod nisl. In sagittis augue turpis, at cursus tellus condimentum in. Morbi vestibulum ultricies enim mattis ultrices. Etiam lobortis interdum ante vitae imperdiet. Phasellus dictum nisl massa, a rutrum quam hendrerit vel.', 'Kenya.jpg');
INSERT INTO blog_posts (blogger_id, post_date, post_title, blog_body, image_src) 
VALUES ('1', '01/03/2022', 'My trip to the Philippines', 'My first time to the Philipinnes! Cannot wait to explore!... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi gravida, massa at varius laoreet, ligula tellus convallis mauris, in dapibus ligula sem in odio. Mauris nisi elit, hendrerit vel diam in, congue molestie nibh. Praesent aliquet metus libero, eget scelerisque nisl ullamcorper ac. Nam eu nunc ex. Fusce ut dignissim felis. Mauris laoreet ante leo, vel aliquam est congue sed. Cras congue lectus vitae justo luctus efficitur. Nunc suscipit diam a felis dapibus gravida. Ut lobortis ultrices venenatis. Nunc aliquam luctus turpis faucibus consectetur. Praesent vitae maximus risus, vitae euismod nisl. In sagittis augue turpis, at cursus tellus condimentum in. Morbi vestibulum ultricies enim mattis ultrices. Etiam lobortis interdum ante vitae imperdiet. Phasellus dictum nisl massa, a rutrum quam hendrerit vel.', 'Philippines.jpg');
INSERT INTO blog_posts (blogger_id, post_date, post_title, blog_body, image_src) 
VALUES ('1', '04/25/2022', 'My trip to Japan', 'What an iconic travel destination! Better enjoy this because travelling to Japan is NOT cheap... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi gravida, massa at varius laoreet, ligula tellus convallis mauris, in dapibus ligula sem in odio. Mauris nisi elit, hendrerit vel diam in, congue molestie nibh. Praesent aliquet metus libero, eget scelerisque nisl ullamcorper ac. Nam eu nunc ex. Fusce ut dignissim felis. Mauris laoreet ante leo, vel aliquam est congue sed. Cras congue lectus vitae justo luctus efficitur. Nunc suscipit diam a felis dapibus gravida. Ut lobortis ultrices venenatis. Nunc aliquam luctus turpis faucibus consectetur. Praesent vitae maximus risus, vitae euismod nisl. In sagittis augue turpis, at cursus tellus condimentum in. Morbi vestibulum ultricies enim mattis ultrices. Etiam lobortis interdum ante vitae imperdiet. Phasellus dictum nisl massa, a rutrum quam hendrerit vel.', 'Tokyo.jpg');


INSERT INTO blog_posts (blogger_id, post_date, post_title, blog_body, image_src) 
VALUES ('2', '03/11/2021', 'Sushi at Msushi', 'This resutaurant in downtown Durham, NC is truly world class... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi gravida, massa at varius laoreet, ligula tellus convallis mauris, in dapibus ligula sem in odio. Mauris nisi elit, hendrerit vel diam in, congue molestie nibh. Praesent aliquet metus libero, eget scelerisque nisl ullamcorper ac. Nam eu nunc ex. Fusce ut dignissim felis. Mauris laoreet ante leo, vel aliquam est congue sed. Cras congue lectus vitae justo luctus efficitur. Nunc suscipit diam a felis dapibus gravida. Ut lobortis ultrices venenatis. Nunc aliquam luctus turpis faucibus consectetur. Praesent vitae maximus risus, vitae euismod nisl. In sagittis augue turpis, at cursus tellus condimentum in. Morbi vestibulum ultricies enim mattis ultrices. Etiam lobortis interdum ante vitae imperdiet. Phasellus dictum nisl massa, a rutrum quam hendrerit vel.', 'Msushi.jpg');
INSERT INTO blog_posts (blogger_id, post_date, post_title, blog_body, image_src) 
VALUES ('2', '05/12/2021', 'A South African Braai', 'If you think a South African Braai is the same as US bbq, think again!... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi gravida, massa at varius laoreet, ligula tellus convallis mauris, in dapibus ligula sem in odio. Mauris nisi elit, hendrerit vel diam in, congue molestie nibh. Praesent aliquet metus libero, eget scelerisque nisl ullamcorper ac. Nam eu nunc ex. Fusce ut dignissim felis. Mauris laoreet ante leo, vel aliquam est congue sed. Cras congue lectus vitae justo luctus efficitur. Nunc suscipit diam a felis dapibus gravida. Ut lobortis ultrices venenatis. Nunc aliquam luctus turpis faucibus consectetur. Praesent vitae maximus risus, vitae euismod nisl. In sagittis augue turpis, at cursus tellus condimentum in. Morbi vestibulum ultricies enim mattis ultrices. Etiam lobortis interdum ante vitae imperdiet. Phasellus dictum nisl massa, a rutrum quam hendrerit vel.', 'Braai.jpg');

INSERT INTO blog_posts (blogger_id, post_date, post_title, blog_body, image_src) 
VALUES ('3', '12/10/2020', 'Deal of the month - Dec 2020', 'This floral top at $7 is to die for!... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi gravida, massa at varius laoreet, ligula tellus convallis mauris, in dapibus ligula sem in odio. Mauris nisi elit, hendrerit vel diam in, congue molestie nibh. Praesent aliquet metus libero, eget scelerisque nisl ullamcorper ac. Nam eu nunc ex. Fusce ut dignissim felis. Mauris laoreet ante leo, vel aliquam est congue sed. Cras congue lectus vitae justo luctus efficitur. Nunc suscipit diam a felis dapibus gravida. Ut lobortis ultrices venenatis. Nunc aliquam luctus turpis faucibus consectetur. Praesent vitae maximus risus, vitae euismod nisl. In sagittis augue turpis, at cursus tellus condimentum in. Morbi vestibulum ultricies enim mattis ultrices. Etiam lobortis interdum ante vitae imperdiet. Phasellus dictum nisl massa, a rutrum quam hendrerit vel.', 'FloralTop.jpg');
INSERT INTO blog_posts (blogger_id, post_date, post_title, blog_body, image_src) 
VALUES ('3', '05/05/2021', 'Deal of the month - May 2021', 'Give me that dress now! At only $30... Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi gravida, massa at varius laoreet, ligula tellus convallis mauris, in dapibus ligula sem in odio. Mauris nisi elit, hendrerit vel diam in, congue molestie nibh. Praesent aliquet metus libero, eget scelerisque nisl ullamcorper ac. Nam eu nunc ex. Fusce ut dignissim felis. Mauris laoreet ante leo, vel aliquam est congue sed. Cras congue lectus vitae justo luctus efficitur. Nunc suscipit diam a felis dapibus gravida. Ut lobortis ultrices venenatis. Nunc aliquam luctus turpis faucibus consectetur. Praesent vitae maximus risus, vitae euismod nisl. In sagittis augue turpis, at cursus tellus condimentum in. Morbi vestibulum ultricies enim mattis ultrices. Etiam lobortis interdum ante vitae imperdiet. Phasellus dictum nisl massa, a rutrum quam hendrerit vel.', 'BlackDress.jpg');
